name: Build

on:
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo 'building...'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: ./node_modules/.bin/ng build --prod
      - name: Scully
        run: npx scully
      - name: Verify
        run: echo ${{ github.repository }}
      - name: Deploy
        run: |
          cp CNAME dist/static
          cd dist/static
          git init
          git config --local user.name 'GitHub Runner'
          git config --local user.email '<>'
          git add .
          git commit -m 'Add static files'
          git remote add origin https://${{ github.actor}}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git >/dev/null 2>&1
          git push --force origin HEAD:static >/dev/null 2>&1
